### ISSUE TITLE
Readme should use --self-contained when converting to HTML

### ISSUE THREAD

**Issue by mcdemarco** [lifelike/pangamebook#1]
It's best to add the pandoc `--self-contained` flag when generating html output:

```pandoc --lua-filter=pangamebook.lua --self-contained -o example.html example.md```

Otherwise the smart quotes pandoc automatically generates do not get the appropriate encoding, and in general the output looks pretty raw.

If you do this, you should also be able to remove the title header line from `example.md` (leaving it in the yaml header).  The redundant titles are a bit confusing.

P.S. I tested on Mac.  Everything else seemed to work fine.

**Comment by lifelike** [comment]
Done. Also did this for the org-mode example (had to add meta-data to set title there). This makes the PDF output look better as well, without duplicate title. Thanks!
