### ISSUE TITLE
-Mgamebook-numbers=false breaks pangamebookdot.lua

### ISSUE THREAD

**Issue by fullstopslash** [lifelike/pangamebook#2]
Firstly let me say I absolutely love this filter! Gamebooks are super cool, the world needs more of them, and you're helping that happen!  So for context I'm using pandoc and pangamebook to design for physically printed booklets.  In the context of a physical book a number heading section makes less sense than referencing the physical page of the book, it's even a bit confusing to parse visually having multiple numbers on a page.  As a side note, I'm mostly using the pangamebookdot.lua filter as a way to map out my progress in filling out the multiple paths the story will go through.  The current limitation of headers only being parsed if they're lowercase was an easy enough change for me personally, but I wanted to start this discussion in order to highlight another small issue.  The other issue I'm seeing is more related to how the script is parsing markdown. Sometimes headers are expressed as `# [Fancy Header Name]{#custom-anchor-name}`, and in it's current implementation this script will always grab the first string instead of the actual anchor, thus rendering any fancy header names and making the flow chart wildly inaccurate.

Either way these scripts will be super useful to me as I run through making drafts! Thanks for this lovely set of tools!  They're immensely useful!

**Comment by lifelike** [comment]
Thanks for the nice comments!

Multiple numbered pagagraphs on each page is very common if you look at some printed gamebooks. Almost all that I have do that and that is also true for more obscure PDF-only gamebooks. There are not many exceptions I can think of (some CYOA books for children and the Tunnels & Trolls solo adventures (although the latter use letters within each page, so on page 3 you find paragraphs 3A, 3B, 3C ... etc... something that pangamebook can not do).

Can you post a more specific example of when a link is wrong? I have not seen that. But it might be a behavior of pandoc. Could be a workaround for that or not.

How does gamebook-numbers=false break? Does it crash? Is there some error printed?

**Comment by fullstopslash** [comment]
My apologies, after examining this further I realized that the problem is with my understanding of how pandoc parses markdown and LaTeX style links, as the behaviour shows up even when pangamebook filters are turned off.  Also, I'm trying to combine LaTeX style links with markdown links and it's getting really involved. My bad!
